### ISSUE TITLE
Scroller上拉无效

### ISSUE THREAD

**Issue by LoveEatChicken** [wdfe/wdui#16]
scroller同时设置了上拉和下拉，结果只有下拉有效，上拉不触发

**Comment by jin5354** [comment]
您好，请提供您在使用的 wdui 版本、相关代码，最好能附上 Demo。
请注意 scroller 组件当前版本只对 touch 事件组进行支持，对 PC 平台的 mouse 事件组响应支持不完善，用鼠标进行上下拉可能出现无效的情况，将在下个小版本添加兼容性。

**Comment by LoveEatChicken** [comment]
您好，上拉不触发的问题解决了，是因为内容没充满container导致的，但是当用了v-if控制scroller显示隐藏，先隐藏再显示会导致无法上拉

**Comment by jin5354** [comment]
@LoveEatChicken 
scroller 若初始内容不足一屏，便不会激活上拉功能。
https://jsfiddle.net/1fy65aw9/ 
我自己写了个 demo，试验了 v-if 下的 scroller 表现应该是正常的，请提供您的 demo 供我参考

**Comment by LoveEatChicken** [comment]
问题已经解决了，感谢您的回复
