### ISSUE TITLE
picker组件当数据到底部时，仍然可以继续滑动？

### ISSUE THREAD

**Issue by wmui** [wdfe/wdui#17]
经测试应该是一个bug，当数据触底时，picker组件无论是上滑还是下拉仍继续滑动，正常情况应该回弹回来，其他组件封装的都很棒。

**Comment by jin5354** [comment]
@wmui 你好，请问可否提供一个 demo？官网 scroller 的示例能否反应出这个问题？

https://jsfiddle.net/udmx0cc7/
可以试试在这个模板上能否复现问题，我核查一下

**Comment by wmui** [comment]
![2017-10-20_213450](https://user-images.githubusercontent.com/24876474/31823381-94e374a4-b5de-11e7-84e0-3da3f724e6da.png)
https://wdfe.github.io/wdui/#/components/picker
scroller组件没问题，官网的picker组件你可以看下，同样有这个问题

**Comment by jin5354** [comment]
@wmui 真不好意思，之前看花眼成 scroller 了😅
感谢反馈，picker 的这个 bug 已在 v0.6.13 版本修正。
