### ISSUE TITLE
Scroller 无限加载组件需支持水平滑动

### ISSUE THREAD

**Issue by yyhappynice** [wdfe/wdui#8]
使用scroller无限加载，顶部tab较长时，不能进行左右滑动～😄

![image](https://user-images.githubusercontent.com/12566627/27114684-d2cfb31e-50f7-11e7-8c19-f890169c2301.png)

**Comment by jin5354** [comment]
@yyhappynice Scroller 组件在外层 DOM 绑定 touchmove 事件接管了滚动行为，若要在 Scroller 内部实现局部滚动，请在内部元素 DOM 上绑定 touchmove 事件并阻止事件冒泡即可。
